services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: saloon-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: esteticacrm
    volumes:
      - ./data/mongo:/data/db
    networks:
      - saloon-network

  # Backend Node.js API
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: saloon-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/esteticacrm
      - JWT_SECRET=your-development-jwt-secret
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - saloon-network

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: saloon-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:3000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - saloon-network

networks:
  saloon-network:
    driver: bridge
